name: store_admin_panel
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  line_icons: ^2.0.1
  flutter_rating_bar: ^4.0.1
  flutter_masked_text2: ^0.9.1
  firebase_storage: ^10.3.3
  dartz: ^0.10.1
  lottie: ^1.3.0
  cloud_firestore: ^3.3.0
  flutter_bloc: ^8.0.1
  dio: ^4.0.6
  image_picker: ^0.8.5+3
  flutter_modular: ^5.0.3
  cached_network_image: ^3.2.1
  mocktail: ^0.3.0
  firebase_core: ^1.19.2
  google_fonts: ^3.0.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  bloc_test: ^9.0.3
  fake_cloud_firestore: ^1.2.2 
  firebase_storage_mocks: ^0.5.1 
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/image-icons/
