// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCG0Fi5gJ2t9RootDaFictarjjK9X3M44',
    appId: '1:540008726527:web:f0155de0e66837a8ca71ca',
    messagingSenderId: '540008726527',
    projectId: 'food-menu-186fa',
    authDomain: 'food-menu-186fa.firebaseapp.com',
    databaseURL: 'https://food-menu-186fa-default-rtdb.firebaseio.com',
    storageBucket: 'food-menu-186fa.appspot.com',
    measurementId: 'G-E0CLGSKSJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS2SxcpQsak8vw9gtLqbKQoQ1gALQVRQ0',
    appId: '1:540008726527:android:4cb134d48ad78e32ca71ca',
    messagingSenderId: '540008726527',
    projectId: 'food-menu-186fa',
    databaseURL: 'https://food-menu-186fa-default-rtdb.firebaseio.com',
    storageBucket: 'food-menu-186fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6QcQM25chGGPL3sGxLwFcdmNYOeiHkAQ',
    appId: '1:540008726527:ios:a77765ff504ab621ca71ca',
    messagingSenderId: '540008726527',
    projectId: 'food-menu-186fa',
    databaseURL: 'https://food-menu-186fa-default-rtdb.firebaseio.com',
    storageBucket: 'food-menu-186fa.appspot.com',
    iosClientId: '540008726527-eugjlj2m21itpeedviefvgcou9b393jk.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6QcQM25chGGPL3sGxLwFcdmNYOeiHkAQ',
    appId: '1:540008726527:ios:a77765ff504ab621ca71ca',
    messagingSenderId: '540008726527',
    projectId: 'food-menu-186fa',
    databaseURL: 'https://food-menu-186fa-default-rtdb.firebaseio.com',
    storageBucket: 'food-menu-186fa.appspot.com',
    iosClientId: '540008726527-eugjlj2m21itpeedviefvgcou9b393jk.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeAdminPanel',
  );
}
